apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: providers-information-pod-disruption-budget
  labels:
    name: providers-information
spec:
  minAvailable: 0
  selector:
    matchLabels:
      name: providers-information
