apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers-information
spec:
  template:
    spec:
      containers:
        - name: providers-information
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: team,$(ENVIRONMENT),$(NAMESPACE),$(ENVIRONMENT)-$(NAMESPACE)
